# Generated by Django 5.2.4 on 2025-08-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_alter_productmovement_date_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
